keepers/sai_maker_otc.py
Since the keeper was designed before the convention "BUY ETH and SELL SAI" was agreed upon for Oasis, the language in the code was the other way around to the one that was ultimately chosen. This renames everything to match Oasis semantics. Moreover, the spread parameter was previously being calculated as a spread from the `gem_per_sai` rate, this commit changes it to be a spread from the `sai_per_gem` rate instead, which is also more intuitive given the Oasis convention. 
Also rename `target_rate()` to `target_price()` to avoid confusion with `way`.
**WARNING: this commit actually changes the meaning of the min,avg,max spread parameters.**
=> Made to match Oasis convention (BUY ETH, SELL SAI). Adjust spread semantics.

api/numeric.py, api/test_numeric.py, api/util.py, keepers/sai_maker_otc.py
For accounting purposes, it's nicer if the keeper places an order for 3210.12 SAI at a price of 321.01 SAI per ETH, instead of 3210.123524345 SAI at a price of 321.012535 SAI per ETH. So we should let the user specify a number of decimal places (defaulting to 2) to round order price to (and possibly also round order size, separately).
I will make more commits (and tests) later, for now we start with rounding `Wad`s.
=> Add (optional) rounding of order price/size

keepers/sai_maker_otc.py
Implemented (separate, optional) SAI and WETH cutoff values to avoid placing and maintaining dust orders. Resolves https://github.com/makerdao/keeper/issues/32
=> Implemented dust cutoffs

README.md
While installing the requirements I realized I was missing `pkg-config`, which seems to be necessary to complete it (at least using `pip3`)
=> Adding necessary package

pymaker/sai.py, tests/test_sai.py
After dai v1 launch, cups parameter order ink and art have changed.
Add a test to cover this case
=> Fix ink and art order for Cup initialisation

pymaker/lifecycle.py
In lifecycle.py, improve string representation of a block hash so it prints as a hex string instead of bytes.
=> Improve string representation of block hash

pymaker/proxy.py, tests/test_proxy.py
- Move the `Address(40*'0')` condition outside test code, returning None on empty cache
- Add code prefix check & update
=> DSProxy & DSProxyCache updates

pymaker/__init__.py, test.sh
This cleans up a bunch of warnings in pyexchange.  Also, updated test.sh to clean up the dangling ganache process.
=> Move away from deprecated Web3 contract.deploy() method.

pymaker/keys.py
This way it's easier to figure out which password shall we enter, as usually different bots will be using different accounts (and so different json files as well).
=> Including the json filename in the password prompt

pymaker/token.py
Airswap uses the regular ethtoken 0x000... this is not an ERC20 contract and therefore breaks when we attempt to pass it into our ERC20Token class.
This addition of the EthToken class allows us to get around this.
=> added EthToken class to token.py

test.sh
fixes #100
- Propagate py.test exit code so Travis CI can catch it
- In addition, `killall` didn't seem to pattern-match the process properly on Mac OS so I've made a few changes to fix it
https://travis-ci.com/Detoo/keeper/builds/118022194 (the test failed as expected)
=> Fix test.sh not reporting py.test result code and ganache-cli process not killed

requirements-dev.txt
`pytest=3.3.0` requires `attrs>=17.2.0`. New virtualenvs now install attrs=19.2.0, which doesn't work with pytest=3.3.0.  Before any tests are run, the following error is produced:
```
Traceback (most recent call last):
File "/home/ed/.local/bin/py.test", line 7, in <module>
from pytest import main
File "/home/ed/.local/lib/python3.6/site-packages/pytest.py", line 13, in <module>
from _pytest.fixtures import fixture, yield_fixture
File "/home/ed/.local/lib/python3.6/site-packages/_pytest/fixtures.py", line 839, in <module>
class FixtureFunctionMarker(object):
File "/home/ed/.local/lib/python3.6/site-packages/_pytest/fixtures.py", line 841, in FixtureFunctionMarker
params = attr.ib(convert=attr.converters.optional(tuple))
TypeError: attrib() got an unexpected keyword argument 'convert'
``` …
=> Fix pytest dependency problem with newer versions of attrs

pymaker/governance.py, tests/test_governance.py
DSChief extends DSChiefApprovals and the public functions therein:
- `lock(uint)`
- `free(uint)`
- `etch(address[])`
- `vote(address[])`
- `vote(bytes32)`
- `lift(address)`
This PR wraps these functions as well as an integration test, covering all but `free(uint)`. As described in the test's comment, the `free()` invocation is reverting because `our_address` needs to give ds-chief approval to move/burn IOU tokens before freeing MKR. Can fix in one of two ways:
1. Need to add IOU (ds-token) to DssDeployment
2. Look for a "mint" event to determine the address of the IOU token when locking MKR
Ref: https://github.com/dapphub/ds-chief/blob/master/src/chief.sol#L65
I'll be using the `pymaker.governance.DSChief` class in https://github.com/makerdao/chief-keeper
=> Wrapped public functions of DSChief

pymaker/__init__.py
We have a keeper lifecycle that’s failing due to a missing `running` attribute on a Thread object: `AttributeError: 'Thread' object has no attribute 'running’`. On the same line that it’s failing, `pymaker` tries to detect when a web3 filter isn’t working, but it assumes that `running` is present. 
As suggested by @grandizzy, it looks more like a general issue where `filter_thread.running` should be replaced with `filter_thread.is_alive()`. 
Unit tests from `tests/test_lifecycle` all pass, and as a mainnet integration test, we've run the `chief-keeper` for a couple weeks with a modified `pymaker` without issue.
=> Update boolean exposed via filter_thread object

pymaker/deployment.py, pymaker/token.py, tests/manual_test_mcd.py, tests/test_dss.py
Added mcd tests to ensure it works for all collaterals.
@grandizzy I resurrected `DssDeployment.from_network`, because I find it taxing to repeatedly swap out JSON configs whenever I switch to a nonstandard set of contracts.  I agree we should point users to `DssDeployment.from_node`, but this feature is very useful to me.
Confirmed travis is happy with this.
=> Resolve issue with token.name() and token.symbol()

pymaker/approval.py, pymaker/auctions.py, pymaker/deployment.py, pymaker/dss.py
I had to rework `hope_directly` to use `pymaker.Transact`.
To test, I used the following code, with commented gas prices observed from etherscan:
```
mcd.approve_dai(our_address)                                          # 16.5 Gwei 16.5 Gwei
collateral.approve(our_address)                                       # 16.5 Gwei 16.5 Gwei
from pymaker.approval import directly, hope_directly
mcd.flopper.approve(mcd.flopper.vat(), hope_directly())               # 14.63 Gwei
from pymaker.gas import FixedGasPrice
gas = FixedGasPrice(39*1000000000)
mcd.approve_dai(our_address, gas_price=gas)                           # 39 Gwei
collateral.approve(our_address, gas_price=gas)
mcd.flopper.approve(mcd.flopper.vat(), hope_directly(gas_price=gas))  # 39 Gwei
```
=> Updated approval functions to take gas strategy

pymaker/dss.py, tests/test_dss.py
This will add support for the following functions based on the current Vat contract implementation:
- `move`: transfer Dai between users
- `flux`: transfer collateral between users
- `fork`: split a Vault - binary approval or splitting/merging Vault's
Function descriptions based on [Maker Vat Glossary](https://github.com/makerdao/dss/wiki/Glossary).
=> Add move, flux and fork support to DSS Vat model

setup.py
makes pymaker available as a python package, so it can be installed via pip or included in a project's requirements file. e.g:
```
pip install git+https://github.com/makerdao/pymaker
```
=> packaging primer

pymaker/model.py, tests/test_model.py
`min_amount` is helpful when dealing with dusty `vat` balances, and makes for more readable code.
=> added min_value property and unit tests for Token class

README.md, pymaker/__init__.py
We discussed this last week.  Feature is disabled by default, and most consumers would never enable it.  Documented in the README.
=> Allow consumer to supply gas limit and submit txs which will fail

pymaker/lifecycle.py, tests/manual_test_node.py
A few times a month, keepers log the following error:
```ValueError: {'code': -32000, 'message': 'Filter not found'}```
followed by
```
2020-05-07 19:34:32,000 CRITICAL No new blocks received for 300 seconds, the keeper will terminate
2020-05-07 19:34:32,001 INFO     Shutting down the keeper
```
[This post](https://ethereum.stackexchange.com/questions/60708/ethereum-web3-filter-not-found) explains nodes can lose filters and _web3.py_ doesn't automatically reestablish them.  Lifecycle uses filters to detect new blocks.
This change catches the exception and recreates the filter.  Difficult to integration test because I couldn't find a way to induce the behavior.
=> recreate filters lost by the node

pymaker/sign.py
This replaces `time.clock` which has been [deprecated](https://docs.python.org/3.6/library/time.html?highlight=process_time#time.clock) since Python 3.3 and has been removed in Python 3.8 with `time.process_time` which is available since Python 3.3.
=> Fix compatibility with Python 3.8

pymaker/deployment.py, tests/manual_test_mcd.py
This is really just to improve consistency with other coins using newer `GemJoin` contracts.  And to improve the manual test for MCD.  
Since there's no interface change, I didn't see a reason to wrap and add artifacts for `GemJoin6`; it would've just added more cruft to the API.  I'm happy to do so if a gas estimation issue for [this call](https://github.com/makerdao/dss-deploy/blob/master/src/join.sol#L370) ever arises.
Tested on kovan only.
=> Gemjoin6\b5

pymaker/__init__.py, tests/manual_test_async_tx.py
`web3.eth.getTransactionCount` still doesn't count transactions in the mempool on OpenEthereum nodes.  Ensure `parity_nextNonce` is used instead.
=> Fix problem with nonces not incrementing on OpenEthereum nodes

pymaker/zrxv2.py
Making this change to specifically get rid of IMtoken errors which occur when syncing all trades. If we send a request to a node and the event that we are looking for `LogFill` doesn't exist we don't return from the method. This PR returns None
=> when we call to check for logs, and none exist ensure we return None

pymaker/gas.py, tests/test_gas.py
Found this corner case when working on `auction-keeper` gas changes.
=> handle case where initial_gas is greater than max_price

pymaker/auctions.py, tests/test_auctions.py
This change facilitates scraping the chain for auction details from a particular point in time.
=> Request auction logs by block range, consistent with past_frobs

pymaker/lifecycle.py, tests/manual_test_node.py
I'm letting Travis run the unit tests.  Also improved the manual node test to not require an address.
=> Improve behavior when the node's block filter encounters a block newer than "current block"

README.md, pymaker/__init__.py, tests/manual_test_async_tx.py, tests/manual_test_tx_recovery.py
The old implementation merely checked if a node was Parity, so it could use `parity_nextNonce` and used `getTransactionCount("pending")` for any non-Parity node.  The new implementation offers a third option, which calls `getTransactionCount` once upon submission of the first transaction, and then atomically increments the nonce for each successive call.  Documented tradeoffs of this approach in the `README`.
=> Implement a serial-incrementing nonce for third-party node providers

pymaker/deployment.py, pymaker/oracles.py, tests/manual_test_mcd.py
It's assumed this will be used for other UNIV2 tokens as well.  Tested on kovan (legit price) and mainnet (0 price untill spell is cast).
=> add support for Univ2LpOracle.sol

pymaker/__init__.py, tests/manual_test_goerli.py, tests/test_auctions.py
Inject `geth_poa_middleware` to create a Web3 instance usable with Goerli.  Doing it here such that all keepers/bots using `web3_via_http` may benefit.  Tested on an Infura Goerli endpoint.
=> add Goerli support

pymaker/__init__.py, tests/test_auctions.py, tests/test_general.py
This PR adds support for generating Calldata from contract_abi, as well as handling erc721 minting transfer event errors in receipt. Mint emits a `Transfer` event which collides with the existing pymaker.receipt expectations.
=> Univ3 pyexchange client changes
